test gh actions

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -32,6 +32,7 @@ jobs:
             # Staging branch
             echo "environment=staging" >> $GITHUB_ENV
             echo "deploy_path=~/../home/projects/augustocode/staging/portfolio" >> $GITHUB_ENV
+            echo "repo_url=git@github.com:Augusto-DF/portfolio.git" >> $GITHUB_ENV  # Update this line
           fi
 
       - name: Deploy to VPS via SSH
@@ -43,12 +44,33 @@ jobs:
           passphrase: ${{ secrets.VPS_PASS }}
           port: 22
           script: |
+            set -e  # Exit immediately if a command exits with a non-zero status
             cd ${{ env.deploy_path }}
-            ${{ secrets.VPS_PASS }}
-            git pull origin ${{ env.environment }}  
-            echo ${{ env.environment }}
-            echo ${{ env.deploy_path }}
-            echo Fim.
-            npm install                            
-            yarn build                          
+            echo "Pulling latest changes..."
+            git pull ${{ env.repo_url }} ${{ env.environment }}  # Use the SSH URL
+
+            # Debugging outputs
+            echo "Current environment: ${{ env.environment }}"
+            echo "Deploy path: ${{ env.deploy_path }}"
+            echo "Finished pulling."
+
+            # Check if npm is installed
+            if command -v npm &> /dev/null; then
+              echo "Installing npm dependencies..."
+              npm install
+            else
+              echo "npm is not installed. Please install Node.js and npm."
+              exit 1
+            fi
+
+            # Check if yarn is installed
+            if command -v yarn &> /dev/null; then
+              echo "Building the project with yarn..."
+              yarn build
+            else
+              echo "yarn is not installed. Please install Yarn."
+              exit 1
+            fi
+
+            echo "Restarting Nginx..."
             sudo systemctl restart nginx
